# Generated by Django 4.0.2 on 2022-02-15 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(verbose_name='Дата и время создания (отправки)')),
                ('status', models.CharField(choices=[('Первоначальный взнос', 'Первоначальный взнос'), ('Пополнение', 'Пополнение'), ('Вступительный взнос', 'Вступительный взнос'), ('Погашение ссуды', 'Погашение ссуды')], default='Первоначальный взнос', max_length=100, verbose_name='Выбор взноса')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing')),
            ],
        ),
    ]
