# Generated by Django 4.0.2 on 2022-02-15 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(verbose_name='Дата и время создания (отправки)')),
                ('status', models.CharField(choices=[('Отправка', 'Отправка'), ('В очереди', 'В очереди'), ('Доставлено', 'Доставлено'), ('Частично доставлено', 'Частично доставлено'), ('Отклонено', 'Отклонено')], default='Отправка', max_length=100, verbose_name='Выбор статуса')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailing.mailing')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
