# Generated by Django 4.0.2 on 2022-02-15 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_options_alter_operatorcode_options_and_more'),
        ('mailing', '0002_alter_mailing_options_remove_mailing_clients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='clients',
        ),
        migrations.CreateModel(
            name='ClientFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='Тег (произвольная метка)')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.operatorcode')),
            ],
        ),
        migrations.AddField(
            model_name='mailing',
            name='client_filter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mailing.clientfilter'),
            preserve_default=False,
        ),
    ]
