# Generated by Django 4.0.2 on 2022-02-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_remove_mailing_clients_clientfilter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfilter',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
