# Generated by Django 4.0.2 on 2022-02-15 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код оператора')),
                ('code_city', models.CharField(max_length=200, verbose_name='Имя оператора')),
            ],
            options={
                'verbose_name': 'Код оператора',
                'verbose_name_plural': 'Код оператора',
            },
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_zone', models.CharField(max_length=50, verbose_name='Часовой пояс')),
                ('time_city', models.CharField(max_length=200, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Часовой пояс',
                'verbose_name_plural': 'Часовой пояс',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='7XXXXXXXX (X - цифра от 0 до 9', max_length=150, verbose_name='Номер телефона клиента')),
                ('tag', models.CharField(max_length=100, verbose_name='Тег (произвольная метка)')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.operatorcode')),
                ('time_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.timezone')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
