# Generated by Django 4.0.2 on 2022-02-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='operatorcode',
            options={'verbose_name': 'Код оператора', 'verbose_name_plural': 'Код оператора'},
        ),
        migrations.AlterModelOptions(
            name='timezone',
            options={'verbose_name': 'Часовой пояс', 'verbose_name_plural': 'Часовой пояс'},
        ),
    ]
